# Automated build and test using GitHub Actions.

name: C++ Initial CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    container: gcc:9.5
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apt-get update && apt-get install -y cmake
    - name: Run syntax check
      run: |
        mkdir build && cd build
        cmake ..
        make

  build-and-test:
    needs: syntax-check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t physics-simulation -f infra/Dockerfile .
    - name: Run Unit-Tests
      run: docker run --rm physics-simulation /usr/src/app/build/bin/unit